name: Build, Push Docker Image to ACR, and Deploy to AKS

on:
  push:
    branches:
      - main  # Adjust the branch as needed

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        run: |
          TOKEN=$(az acr login --name DevOpsProjectLambton --expose-token --output tsv --query accessToken)
          echo $TOKEN | docker login DevOpsProjectLambton.azurecr.io -u 00000000-0000-0000-0000-000000000000 --password-stdin

      - name: Get Git Commit ID
        id: git_commit_id
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push image to ACR
        run: |
          IMAGE_NAME=DevOpsProjectLambton.azurecr.io/myapp:${{ env.commit_id }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Tag latest
        run: |
          docker tag DevOpsProjectLambton.azurecr.io/myapp:${{ env.commit_id }} DevOpsProjectLambton.azurecr.io/myapp:latest
          docker push DevOpsProjectLambton.azurecr.io/myapp:latest

      - name: Create namespace if not exists
        run: |
          kubectl get namespace dev || kubectl create namespace dev

      - name: Deploy to AKS
        run: |
          sed -i 's|{{IMAGE_TAG}}|${{ env.commit_id }}|g' k8s-manifest.yaml
          kubectl apply -f k8s-manifest.yaml